apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-project
  template:
    metadata:
      labels:
        app: cicd-project
    spec:
      containers:
      - name: cicd-project
        image: evil08/cicd-project:latest
        ports:
        - containerPort: 3000
